# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 子阅
email: liuhao1990@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   每天一篇高质量技术文章
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ziyue.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
paginate: 3
paginate_path: "/:num/"

gems:
  - jekyll-sitemap
  - jekyll-paginate